package com.pz.demo.DataBase;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class TestData {
    private RodzajsubstancjiRepository rodzajsubstancjiRepository;
    private SubstancjaRepository substancjaRepository;

@Autowired
    public TestData(RodzajsubstancjiRepository rodzajsubstancjiRepository, SubstancjaRepository substancjaRepository) {

        this.rodzajsubstancjiRepository = rodzajsubstancjiRepository;
        this.substancjaRepository = substancjaRepository;
    }

    public void loadData() {

        this.rodzajsubstancjiRepository.deleteAll();
        this.substancjaRepository.deleteAll();

        this.rodzajsubstancjiRepository.save(Rodzajsubstancji.builder().nazwaRodzaju("ciecz").build());
        this.rodzajsubstancjiRepository.save(Rodzajsubstancji.builder().nazwaRodzaju("gaz").build());
        this.rodzajsubstancjiRepository.save(Rodzajsubstancji.builder().nazwaRodzaju("stala").build());



        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Amoniak").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("gaz").getIdRodzaju()).opis("Jest gazem bezbarwnym, silnie żrącym, trującym i palnym w każdej temperaturze. W zetknięciu z niektórymi substancjami stwarza zagrożenie wybuchowe. Jest lżejszyod powietrza, co sprzyja gromadzeniu się go w górnych partiach pomieszczeń. Działa silnie drażniąco na błony śluzowe dróg oddechowych, oczy i na skórę. Wywołuje przykre uczucie pieczenia w gardle, kaszel, ślinotok, nudności, łzawienie, bóle głowy. Przy wyższych stężeniach wywołuje obrzęk płuc, niewydolność krążenia, zapaść i śmierć. Roztwory wodne są żrące i trujące.").urlObrazka("http://i37.tinypic.com/5megax.jpg").urlFilmu("https://www.youtube.com/embed/eNsz_cxIuDk?ecver=2").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Chlor").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("gaz").getIdRodzaju()).opis("Jest gazem o barwie zielonożółtej. Posiada ostry, duszący zapach. Jest cięższy od powietrza. Po wydostaniu się ze zbiornika szybko odparowuje tworząc ciężki obłok ścielący się tuż nad powierzchnią ziemi. Powoduje podrażnienia błon śluzowych oczu, nosa, górnych dróg oddechowych. Wywołuje łzawienie, kichanie, ślinotok i kaszel - połączone z bólami głowy i w okolicy mostka. Przy wyższych stężeniach występuje obrzęk płuc i śmierć.").urlObrazka("http://gotexassoccer.com/elements/017Cl/Cl_DSCN3511.jpg").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Propan").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("gaz").getIdRodzaju()).opis("Gaz szkodliwy, skrajnie łatwopalny, z powietrzem tworzy mieszaniny wybuchowe. Propan jest trzecim w szeregu homologicznym łańcuchowym węglowodorem nasyconym. W warunkach naturalnych jest to bezbarwny gaz, cięższy od powietrza, o charakterystycznym zapachu. Propan rozpuszcza się w wodzie oraz w alkoholu i eterze. Posiada zdolność do tworzenia roztworów z olejami mineralnymi. Substancja chemicznie stabilna. Nie działa na metale korodująco. Propan występuje w gazie ziemnym i ropie naftowej. GAZ SKARAJNIE ŁATWOPALNY, PARY TWORZĄ Z POWIETRZEM MIESZANINY WYBUCHOWE. PARY SĄ CIĘŻSZE OD POWIETRZA - GROMADZĄ SIĘ PRZY POWIERZCHNI I W DOLNYCH PARTIACH POMIESZCZEŃ. Na organizm człowieka działa umiarkowanie szkodliwie. W wyższych stężeniach wykazuje działanie narkotyczne.").urlObrazka("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Propane-3D-balls-B.png/220px-Propane-3D-balls-B.png").urlFilmu("https://www.youtube.com/embed/hwevCk0SFfc?ecver=2").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Formaldehyd").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("gaz").getIdRodzaju()).opis("Gaz drażniący, trucizna ogólnoustrojowa, z powietrzem tworzy mieszaniny wybuchowe, substancja rakotwórcza NOTA B, NOTA D. Formaldehyd w warunkach normalnych jest to bezbarwny gaz, o charakterystycznym, gryzącym zapachu. Z powietrzem tworzy mieszaniny wybuchowe w granicach stężeń 7 do 73%. Tak duża rozpiętość stężeń czyni formaldehyd bardzo niebezpiecznym gazem. Dobrze rozpuszcza się w wodzie, alkoholu, eterze, węglowodorach, terpentynie. Formaldehyd jest gazem trującym. Posiada silne właściwości bakteriobójcze. W organizmy żywe wchodzi w reakcje z większością składników komórkowych, doprowadzając do uszkodzenia i obumarcia komórek.").urlObrazka("https://1.bp.blogspot.com/-O_2IUROHyAg/Wk9rfgTZ-dI/AAAAAAAAEic/1e5fHj3GKkMu3HGK5DljS4CHqLFAie8mQCLcBGAs/s1600/Formaldehyd.png").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Kwas siarkowy").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("ciecz").getIdRodzaju()).opis("W warunkach normalnych kwas siarkowy 92% jest bezbarwną oleistą cieczą, o właściwościach żrących. Kwas siarkowy dobrze rozpuszcza się w wodzie i miesza sięz nią w każdym stosunku z wydzielaniem dużej ilości ciepła. Należy do środków silnie szkodliwych i niebezpiecznych dla zdrowia. Na wszystkie tkanki działa silnie drażniącooraz żrąco. Wchłania się do organizmu przez drogi oddechowe i układ pokarmowy.Oblanie dużej powierzchni ciała kwasem 92% może spowodować wstrząs. ").urlObrazka("https://nowa.e-pat.pl/userdata/gfx/3fce3c768b48dca9b6b3a42e12f8f92c.jpg").urlFilmu("https://www.youtube.com/embed/fLHGnax7bD8?ecver=2").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Kwas solny").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("ciecz").getIdRodzaju()).opis("Kwas solny jest substancją ciekłą, żrącą, wydzielającą trujące i żrące pary, działającym korodująco. W warunkach normalnych jest bezbarwną lub lekko żółtą cieczą, dymiącą na powietrzu. Mocny kwas bardzo czynny chemicznie. Kwas solny reaguje z większością metali z wydzielaniem wodoru, co stwarza zagrożenie wybuchem.").urlObrazka("http://www.chemik24.pl/files/fotob/product-1254.jpg").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Kwas azotowy").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("ciecz").getIdRodzaju()).opis("Kwas azotowy 100% jest w warunkach normalnych bezbarwną, ruchliwą cieczą o specyficznym zapachu, zabarwiającą się czasem na kolor żółty w skutek zachodzących procesów rozkładu, z wydzieleniem dwutlenku azotu. Kwas azotowy jest mocnym kwasem, substancją niepalną. Posiada właściwości silnie utleniające. Kwas azotowy w zetknięciu z alkoholem etylowym i terpentyną wybucha. W reakcjach z metalami , niemetalami i wieloma związkami ulega redukcji do dwutlenku lub tlenku azotu, utleniając te metale (z wyjątkiem metali szlachetnych). Kwas azotowy należy do środków silnie szkodliwych i niebezpiecznych dla zdrowia. Na wszystkie tkanki działa silnie toksycznie, drażniąco oraz żrąco.").urlObrazka("http://gaz-bud.pl/591-large_default/kwas-azotowy-65.jpg").urlFilmu("https://www.youtube.com/embed/k7cnFwJOxTY?ecver=2").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Benzyna").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("ciecz").getIdRodzaju()).opis("W warunkach normalnych jest bezbarwną, przezroczystą cieczą o charakterystycznym zapachu dla mieszaniny węglowodorów alifatycznych i nasyconych aromatycznych. Substancja ŁATWO PALNA. Tworzy z powietrzem mieszaniny wybuchowe. Nie rozpuszcza się w wodzie, dobrze zaś w rozpuszczalnikach organicznych, jak np.: w acetonie, alkoholu, eterze. ").urlObrazka("https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Gasoline_in_mason_jar.jpg/200px-Gasoline_in_mason_jar.jpg").urlFilmu("https://www.youtube.com/embed/d4wTUf6xs34?ecver=2").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Metanol").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("ciecz").getIdRodzaju()).opis("Alkohol metylowy, spirytus drzewny rektyfikowany. Środek toksyczny, łatwopalny, z powietrzem tworzy mieszaniny wybuchowe. Metanol w warunkach normalnych jest bezbarwną cieczą o aromatycznym zapachu, podobnym do alkoholu etylowego. Wdychanie przez człowieka par metanolu lub bezpośrednie jego spożycie, doprowadza do porażenia systemu nerwowego (działania narkotyczne), utraty wzroku a często doprowadza do śmierci. ").urlObrazka("http://nextews.com/images/6f/d1/6fd198d17f0c0ee6.jpg").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Cyjanek potasu").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("stala").getIdRodzaju()).opis("W warunkach normalnych jest białym, krystalicznym proszkiem rozpływającym się na powietrzu, o zapachu gorzkich migdałów. Pod wpływem kwasów mineralnych i organicznych oraz wilgoci, cyjanek potasu rozkłada się szybko z wydzieleniem silnie toksycznego cyjanowodoru, który tworzy mieszaniny wybuchowe z powietrzem. Roztwory wodne mają odczyn silnie alkaiczny. Cyjanek potasu jest silną trucizną. Zatrucie może nastąpić na drodze pokarmowej, poprzez wdychanie par i płynów, a także przez wilgotną skórę lub zranienia. Działa szybko doprowadzając na ogół do śmierci. Dawka śmiertelna 2 mg/kg wagi człowieka.").urlObrazka("https://upload.wikimedia.org/wikipedia/commons/d/d0/Potassium-cyanide-phase-I-unit-cell-3D-SF.png").build());
        this.substancjaRepository.save(Substancja.builder().nazwaSubstancji("Wodorotlenek sodu").idKategorii(this.rodzajsubstancjiRepository.findRodzajsubstancjiByNazwaRodzaju("stala").getIdRodzaju()).opis("W warunkach normalnych wodorotlenek sodowy jest białym lub bezbarwnym ciałem stałym rozpływającym się w powietrzu. Substancja ta nie ma zapachu. W przemyśle i handlu występuje pod nazwami: wodorotlenek sodowy, soda żrąca, soda kaustyczna, kaustyk. Stosowany jest w postaci roztworów wodnych, wodno-alkoholowych i alkoholowych. Taki roztwór nosi nazwę ługu sodowego. Rozpuszczaniu wodorotlenku sodowego w wodzie towarzyszy wydzielanie dużej ilości ciepła. Ług sodowy atakuje metale, takie jak: cyna, cynk i glin. W wyniku reakcji powstaje wodór, który z powietrzem tworzy mieszaninę wybuchową. ").urlObrazka("http://static.scholaris.pl/resource-files/257/45666/wodorotlenek-sodu_64955.jpg").urlFilmu("https://www.youtube.com/embed/7aMmuOCYazc?ecver=2").build());


}

    public void printData() {
        System.out.println("Substancja");
        System.out.println("---------------------------------------");
        for (Substancja substancja : this.substancjaRepository.findAll()) {
            System.out.println(substancja.getNazwaSubstancji());
        }
        System.out.println();

    }

}